name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Online Document
      run: |
        git config --global user.email "zhang.jianyu@outlook.com"
        git config --global user.name "ZhangJianyu"
        cd build_docs
        bash build.sh
